spring.application.name=api

# -----------------------------------------------
# Database PostgreSQL + PostGIS
# -----------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_db
#spring.datasource.url=jdbc:postgresql://db:5432/sistema_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000


# Flyway fica habilitado por padrão, mas você pode ser explícito:
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Com Flyway, o Hibernate NÃO deve gerenciar o schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

# Dialeto com suporte a tipos espaciais (PostGIS)
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

# -----------------------------------------------
# Server
# -----------------------------------------------
server.port=8080

# -----------------------------------------------
# Jackson
# -----------------------------------------------
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# -----------------------------------------------
# JWT
# secret: string Base64 de 256 bits (32 bytes)
# Gere um novo com: openssl rand -base64 32
# -----------------------------------------------
security.jwt.secret=bXktc2VjcmV0LWtleS1mb3ItcnN0YWxvZy1hcGktMjAyNQ==
security.jwt.expiration-ms=86400000
