CREATE TABLE customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(150)                            NOT NULL,
    tax_id     VARCHAR(14),
    type       VARCHAR(20)                             NOT NULL,
    email      VARCHAR(150),
    phone      VARCHAR(20),
    address    VARCHAR(200),
    city       VARCHAR(100),
    state      VARCHAR(2),
    active     BOOLEAN                                 NOT NULL,
    location   GEOGRAPHY(POINT, 4326),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE distributors
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    legal_name     VARCHAR(150)                            NOT NULL,
    trade_name     VARCHAR(150),
    tax_id         VARCHAR(18),
    address        VARCHAR(200),
    city           VARCHAR(100),
    state          VARCHAR(2),
    phone          VARCHAR(20),
    email          VARCHAR(150),
    contact_person VARCHAR(200),
    active         BOOLEAN                                 NOT NULL,
    location       GEOGRAPHY(POINT, 4326),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_distributors PRIMARY KEY (id)
);

CREATE TABLE inventory
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    current_quantity INTEGER                                 NOT NULL,
    minimum_quantity INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory PRIMARY KEY (id)
);

CREATE TABLE inventory_movements
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    type             VARCHAR(10)                             NOT NULL,
    quantity         INTEGER                                 NOT NULL,
    reason           VARCHAR(300),
    previous_balance INTEGER                                 NOT NULL,
    current_balance  INTEGER                                 NOT NULL,
    order_id         BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inventory_movements PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    unit_price DECIMAL(10, 2)                          NOT NULL,
    subtotal   DECIMAL(12, 2)                          NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    distributor_id BIGINT                                  NOT NULL,
    status         VARCHAR(20)                             NOT NULL,
    notes          VARCHAR(500),
    total_amount   DECIMAL(12, 2)                          NOT NULL,
    delivery_route GEOMETRY(LINESTRING, 4326),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(150)                            NOT NULL,
    description     VARCHAR(500),
    price           DECIMAL(10, 2)                          NOT NULL,
    category        VARCHAR(100),
    unit_of_measure VARCHAR(50),
    active          BOOLEAN                                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(150)                            NOT NULL,
    email      VARCHAR(150)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    active     BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_taxid UNIQUE (tax_id);

ALTER TABLE distributors
    ADD CONSTRAINT uc_distributors_taxid UNIQUE (tax_id);

ALTER TABLE inventory
    ADD CONSTRAINT uc_inventory_product UNIQUE (product_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE inventory_movements
    ADD CONSTRAINT FK_INVENTORY_MOVEMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE inventory_movements
    ADD CONSTRAINT FK_INVENTORY_MOVEMENTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_DISTRIBUTOR FOREIGN KEY (distributor_id) REFERENCES distributors (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);